# mystr ="pakistan is my best country"
# print(mystr)
# # print(mystr[0:4])
# # print(len(mystr))
# # print(mystr[0:10:2])
# # print(mystr[::2])
# # print(mystr[-5:-20])
# # print(mystr.isalpha())
# # print(mystr.endswith("country"))
# # print(mystr.count("a"))
# # print(mystr.capitalize())
# # print(mystr.upper())
# # print(mystr.replace("is","are"))
# # print(mystr.isalpha())
# # print(mystr.endswith("country"))
# # print(mystr.count("a"))
# # print(mystr.replace("is","are"))
# print(mystr.upper())